### PR TITLE
sample data uploaded

### PR DESCRIPTION
**Pull request by Gnuaz**

### CODE REVIEW

**Comment by jshlee** [comment]
not good to add large data to git

**Comment by Gnuaz** [comment]
I think just 1 period data is not bad, and size of 2 data is almost 50- MB

2017-09-07 13:27 GMT+09:00 Jason Lee <notifications@github.com>:

**Comment by jshlee** [comment]
still too big.
cloning will take a long time later on.
just use the first 100 lines of each file.

**Comment by Gnuaz** [comment]
okay I will.

**Pull request closed without merging**
